export enum OrgPlan {
  STUDIO = 'STUDIO',
  ENTERPRISE = 'ENTERPRISE',
  HUMANOID = 'HUMANOID',
}

export enum UserRole {
  OWNER = 'OWNER',
  ADMIN = 'ADMIN',
  MEMBER = 'MEMBER',
}

export enum SurrogateStatus {
  DRAFT = 'DRAFT',
  ACTIVE = 'ACTIVE',
  PAUSED = 'PAUSED',
  ARCHIVED = 'ARCHIVED',
}

export enum SOPStatus {
  DRAFT = 'DRAFT',
  REVIEW = 'REVIEW',
  CERTIFIED = 'CERTIFIED',
  DEPRECATED = 'DEPRECATED',
}

export enum AuditAction {
  SURROGATE_CREATED = 'SURROGATE_CREATED',
  SURROGATE_UPDATED = 'SURROGATE_UPDATED',
  SURROGATE_DELETED = 'SURROGATE_DELETED',
  SOP_CREATED = 'SOP_CREATED',
  SOP_UPDATED = 'SOP_UPDATED',
  SOP_CERTIFIED = 'SOP_CERTIFIED',
  SOP_DEPRECATED = 'SOP_DEPRECATED',
  USER_LOGIN = 'USER_LOGIN',
  USER_REGISTERED = 'USER_REGISTERED',
  ORG_UPDATED = 'ORG_UPDATED',
  MEMBER_INVITED = 'MEMBER_INVITED',
  MEMBER_REMOVED = 'MEMBER_REMOVED',
  ESCALATION_TRIGGERED = 'ESCALATION_TRIGGERED',
  DECISION_MADE = 'DECISION_MADE',
  OVERRIDE_APPLIED = 'OVERRIDE_APPLIED',
}

export enum SurrogateInterface {
  CHAT = 'CHAT',
  VOICE = 'VOICE',
  AVATAR = 'AVATAR',
  API = 'API',
  HUMANOID = 'HUMANOID',
  IOT = 'IOT',
}

export enum SOPNodeType {
  INFORMATION_GATHER = 'INFORMATION_GATHER',
  ASSESSMENT = 'ASSESSMENT',
  DECISION = 'DECISION',
  ACTION_DIGITAL = 'ACTION_DIGITAL',
  ACTION_PHYSICAL = 'ACTION_PHYSICAL',
  CHECKPOINT = 'CHECKPOINT',
  ESCALATION = 'ESCALATION',
  DOCUMENTATION = 'DOCUMENTATION',
  HANDOVER = 'HANDOVER',
}
